### ISSUE TITLE
Direct link to provider

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-register#37]
@mritzmann
> It would be great if a provider could be preselected with a get parameter.
> 
> Example:
> 
> * `https://nextcloud.com/signup/?provider=webo.hosting`
> * `https://nextcloud.com/signup/?provider=snowflakeOps`
> 
> This allows providers/users to refer/link directly to Nextcloud Easy sign up with a preselectet provider.

**Comment by mritzmann** [comment]
Any Update on this?

**Comment by skjnldsv** [comment]
@mritzmann sorry about the delay, I forgot about this one!
This is implemented and will be released on our next deployment :)
