### ISSUE TITLE
Unable to choose a provider

### ISSUE THREAD

**Issue by DodoLeDev** [nextcloud/nextcloud-register#555]
### Hi everyone!
On the [Simple Sign up webpage](https://nextcloud.com/sign-up/), we are unable to select a provider on the list… because **there is no list**!
Just an image, which seems to act as a placeholder…

![The provider list is just an image!](https://i.imgur.com/qJz1VKz.jpeg)

_Please fix this issue, I can't register on my favourite service because it requires using that simple signup method!_

**Comment by skjnldsv** [comment]
Fixed long time ago, forgot to close
